/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentation: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */


  documentation: [
   // {
   //   type: "category",
   //   label: "FAQ",
   //   items : [
   //     "faq/2022-05-01-customer-follow-up-can-be-empty",
   //   ]
   // },

    {
       type: "doc",
       id: "faq",
       label: " FAQ",
    },

    {
      type: "doc",
      id: "systemoverview",
      label: "System Overview",
    },

    {
      type: "doc",
      id: "basicoperation",
      label: "Basic Operation",
    },

    {
      type: "doc",
      id: "general",
      label: "General",
    },

    {
      type: "doc",
      id: "mraog",
      label: "MRA Operational Guide",
    },
//
//    //{
//    //  type: "doc",
//    //  id: "saog",
//    //  label: "SERVICE ADVISOR Operational Guide"
    //},

    {
      type: "doc",
      id: "general-repair/security-gate/security-gate",
      label: "Security Gate",
    },

    {
      type: "doc",
      id: "general-repair/reception/reception",
      label: "Reception",
    },

    {
      type: "doc",
      id: "general-repair/job-distribution/job-distribution",
      label: "Job Distribution",
    },

    {
      type: "doc",
      id: "general-repair/production/production",
      label: "Production",
    },

    {
      type: "doc",
      id: "general-repair/inspection/inspection",
      label: "Inspection",
    },

    {
      type: "doc",
      id: "general-repair/doc-checking/doc-checking",
      label: "Document Checking",
    },

    {
      type: "doc",
      id: "general-repair/invoicing/invoicing",
      label: "Invoice",
    },

    {
      type: "doc",
      id: "general-repair/exit-permit/exit-permit",
      label: "Exit Permit",
    },

    {
      type: "doc",
      id: "general-repair/cash-receipt/cash-receipt",
      label: "Payment",
    },

    {
      type: "doc",
      id: "general-repair/follow-up/follow-up",
      label: "Follow Up",
    },

    //{
    //  type: "category",
    //  label: "General Repair",
    //  items : [
        //"general-repair/create-booking/create-booking",
        //"general-repair/security-gate/security-gate",
        //"general-repair/reception/reception",
        //"general-repair/create-wo/create-wo",
        //"general-repair/wac/wac",
        //"general-repair/print-wo/print-wo",
        //"general-repair/job-distribution/job-distribution",
        //"general-repair/production/production",
        //"general-repair/service-part-supply/service-part-supply",
        //"general-repair/inspection/inspection",
        //"general-repair/doc-checking/doc-checking",
        //"general-repair/invoicing/invoicing",
        //"general-repair/exit-permit/exit-permit",
        //"general-repair/cash-receipt/cash-receipt",
  //    ]
  //  },
//
//    {
//      type: "category",
//      label: "Purchase Part",
//      items : [
//        "purchase-part/create-wo/create-wo",
//        "purchase-part/print-wo/print-wo",
//        //"purchase-part/service-part-supply/service-part-supply",,
//        "purchase-part/doc-checking/doc-checking",
//        "purchase-part/invoicing/invoicing",
//        //"purchase-part/gate-pass/gate-pass",
//        "purchase-part/cash-receipt/cash-receipt",
//      ]
//    },
//
//    {
//      type: "category",
//      label: "Body Painting",
//      items : [
//        "body-painting/security-gate/security-gate",
//        "body-painting/reception/reception",
//        "body-painting/create-wo/create-wo",
//        "body-painting/wac/wac",
//        "body-painting/print-wo/print-wo",
//        "body-painting/job-distribution/job-distribution",
//        "body-painting/production/production",
//        "body-painting/service-part-supply/service-part-supply",
//        "body-painting/inspection/inspection",
//        "body-painting/doc-checking/doc-checking",
//        "body-painting/invoicing/invoicing",
//        "body-painting/gate-pass/gate-pass",
//        "body-painting/cash-receipt/cash-receipt",
//      ]
//    },
//
    //{
    //  type: "category",
    //  label: "PART OPERATIONAL GUIDE",
    //  items: [
    //    "partman-og/service-part-supply/service-part-supply",
    //  ]
    //},

    {
      type: "doc",
      id: "partmanog",
      label: "PART Operational Guide",
    },

    {
      type: "doc",
      id: "general-repair/approval/approval",
      label: "Approval",
    },


    {
      type: "doc",
      id: "general-repair/change-sa/change-sa",
      label: "Change Service Advisor",
    },

    {
      type: "doc",
      id: "reports",
      label: "Reports",
    },

    //{
    //  type: "doc",
    //  id: "billingog",
    //  label: "BILLING Operational Guide"
    //},

  ],


};

module.exports = sidebars;